service: slack-invite

provider:
  name: aws
  runtime: nodejs4.3
  stage: prod
  region: us-east-1

functions:
  slack-invite:
    handler: handler.invite
    name: slack-invite
    events:
      - http:
          path: slack/invite
          method: post
          authorizer: google-recaptcha
          cors: true
          integration: lambda
          response:
            passthrough: NEVER
    environment:
      token: ${file(slack-invite.json):token}
      team: ${file(slack-invite.json):team}
      channels: ${file(slack-invite.json):channels}

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
